# Configuración de respaldo para pruebas
BACKUP_DIRS="/etc/hostname /etc/hosts"
BACKUP_NAME="servidor_prueba"
EXCLUDE_PATTERNS="*.tmp"
SYSADMIN_NAME="Admin Prueba"
BACKUP_DESCRIPTION="Respaldo de prueba"
